version: '3.5'
services:
    db:
        build:
            dockerfile: ./src/main/java/database/Dockerfile
        container_name: db
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - localnet
        volumes:
            - bot_db:/var/lib/postgresql/data
    bot:
        build:
            dockerfile: ./Dockerfile
        container_name: bot
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - localnet
        volumes:
            - /logs:/logs
        depends_on:
            - db
networks:
    localnet:
        external: true
volumes:
    bot_db:
        external: true